name: Update

on:
  push:
    branches:
      - main
    paths:
      - "_data/*.yml"
      - ".github/workflows/update.yml"
  workflow_dispatch:
  schedule:
    - cron: '* */1 * * *' # 1시간 마다

jobs:
  CSS:
    runs-on: windows-latest
    steps:
      - name: Checkout metadata
        uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Update CSS
        run: "pnpm update:css"
      - name: Upload bucket
        uses: EndBug/add-and-commit@v9
        with:
          add: buckets
          default_author: github_actor
          message: "chore(deps): update buckets"
